Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace PensioenfederatieSite.Controllers
{
    public class PollController : SurfaceController
    {

        [HttpPost]
        public ActionResult Submit(RenderModelBinder model)
        {

            string result = "";

            if (!Request.Form.AllKeys.Contains("answerlist"))
            {
                return Content("Make your chose in poll");
            }

            int answernodeid = Convert.ToInt32(Request.Form.GetValues("answerlist")[0]);
            var cs = Services.ContentService;

            var answernode = cs.GetById(answernodeid);
            var pollnode = cs.GetById(answernode.ParentId);
            int allvote = 0;

            int votes = Convert.ToInt32(answernode.GetValue("vote"));
            votes = ++votes;
            answernode.SetValue("vote", votes);
            cs.SaveAndPublishWithStatus(answernode);


            foreach (var item in cs.GetChildren(pollnode.Id))
            {
                result = result + (String.Format("answer {0}) votes {1}", item.Id.ToString(), (Convert.ToInt32(item.GetValue("vote")).ToString())));
                allvote = allvote + Convert.ToInt32(item.GetValue("vote"));
            }

            result = result + "  Totale votes =" + allvote;

            return Content(result);

        }



    }
}

Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    Layout = "Master.cshtml";
}

<div>

    @{
        var selection = Model.Content.Descendants("trend").Where("Visible").FirstOrDefault();

        if (selection != null)
        {

            Response.Redirect(selection.Url,true);
        }
    }
</div>



    @*<section class="section slider preload-hidden">
        <div id="jx-slider-1"></div>
    </section>
    <section class="section slider preload-hidden">
        <div id="jx-slider-2"></div>
    </section>
    <section class="section text preload-hidden">
        <div class="content">
            <h2>
                EEN BAAN VOOR HET <span>LEVEN IS VERANDERD IN</span> Leven vol met banen
            </h2>
            <p>
                Een baan voor het leven is veranderd in een leven vol banen. We switchen makkelijk van baan, maar ook van sector. Soms zitten we zelfs even zonder werk en we beginnen steeds vaker als zelfstandige.
            </p>
        </div>
    </section>
    <section class="section text faded skew-inversed preload-hidden">
        <div class="content">
            <div class="uk-table uk-text-right">
                <div>
                    <h3 class="counter">35</h3>
                    <p>
                        procent van de mensen tussen de 25 en 35 jaar bouwt bij meer dan twee fondsen pensioen.
                    </p>
                </div>
                <div>@Umbraco.Media(1029).Url<img src="@Umbraco.Media(1143).Url" alt="35" title="35"></div>
            </div>
            <div class="uk-table uk-text-left">
                <div>
                    <h3 class="counter">15</h3>
                    <p>
                        procent van de mensen tussen de 25 en 35 jaar werkt als ZZP’er.
                    </p>
                </div>
                <div><img src="@Umbraco.Media(1141).Url" alt="15" title="35"></div>
            </div>
        </div>
    </section>
    <section class="section slider compact preload-hidden">
        <div id="jx-slider-3"></div>
        <div class="widget">
            <div class="content">
                <p>
                    Steeds meer mensen hebben steeds meer verschillende pensioenpotjes. De kans is ook groot dat je tussen die potjes ‘onderbrekingen’ hebt; periodes dat je geen pensioen hebt opgebouwd.
                </p>
                <div class="widget-intreaction">
                    <form class="uk-form">
                        <h4>Hoeveel % van de beroepsbevolking denk je dat zzp’er is?</h4>
                        <p>Selecteer hieronder uw antwoord</p>
                        <div class="uk-form-row">
                            <input type="radio" name="vote" id="vote_5">
                            <label for="vote_5">5%</label>
                        </div>
                        <div class="uk-form-row">
                            <input type="radio" name="vote" id="vote_10">
                            <label for="vote_10">10%</label>
                        </div>
                        <div class="uk-form-row">
                            <input type="radio" name="vote" id="vote_15">
                            <label for="vote_15">15%</label>
                        </div>
                        <div class="uk-form-row">
                            <input type="submit" value="Stem" class="uk-button uk-button-primary uk-button-large">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section slider preload-hidden">
        <div class="uk-grid">
            <div class="uk-width-1-5">
                <div class="uk-table">
                    <div class="uk-cell">
                        <div class="content">
                            <h2>
                                GOED OM
                                <span>TE WETEN</span>
                            </h2>
                            <p>Je werkt 1 dag voor je pensioen</p>
                        </div>
                    </div>
                </div>

            </div>
            <div class="uk-width-3-5">
                <div id="jx-slider-4"></div>
            </div>
            <div class="uk-width-1-5">
                <div class="uk-table">
                    <div class="uk-cell">
                        <div class="content">
                            <h2>
                                GOED OM
                                <span>TE DOEN</span>
                            </h2>
                            <p>
                                Check jouw verschillende pensioenpotjes op
                                <a href="http://mijnpensioenoverzicht.nl">mijnpensioenoverzicht.nl</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section clean partial widgets preload-hidden">
        <div class="title">
            <h2>
                Leef je van dag tot dag
                <span>Of kijk je verder vooruit?</span>
            </h2>
        </div>
        <div class="uk-grid">
            <div class="uk-width-1-3 skew fb">
                <div class="content">
                    <p>
                        Blijf op de hoogte <br>via Facebook.
                    </p>

                    <div class="uk-text-center">
                        <img src="@Umbraco.Media(1133).Url" alt="Facebook" title="Facebook">
                        <br>
                        <a href="#" class="uk-button uk-button-primary uk-button-large">Naar facebookpagina</a>
                    </div>

                </div>
            </div>
            <div class="uk-width-1-3 skew subscribe">
                <div class="content">
                    <p>
                        Op mijnpensioenoverzicht.nl kun je snel <br>en simpel checken hoe jij ervoor staat.
                    </p>
                    <div class="uk-text-center">
                        <img src="@Umbraco.Media(1137).Url" alt="mijnpensioenoverzicht.nl" title="mijnpensioenoverzicht.nl">
                        <br>
                        <a href="http://mijnpensioenoverzicht.nl" class="uk-button uk-button-default uk-button-large">
                            <span>mijn</span>pensioenoverzicht.nl
                        </a>
                    </div>
                </div>
            </div>
            <div class="uk-width-1-3 skew contact">
                <div class="content">
                    <form class="uk-form">
                        <p>
                            Schrijf je in voor <br>
                            De Tijd van Je Leven nieuwsbrief.
                        </p>
                        <div class="uk-form-row">
                            <input type="text" name="email" placeholder="Uw voor en achternaam">
                        </div>
                        <div class="uk-form-row">
                            <input type="password" name="email" placeholder="Uw emailadres@voorbeeld.iets">
                        </div>
                        <div class="uk-form-row">
                            <input type="submit" class="uk-button uk-button-primary uk-button-large" value="aanmelden">
                        </div>
                    </form>
                    <img src="@Umbraco.Media(1138).Url" class="hover-view">
                </div>
            </div>
        </div>
    </section>
    <section class="section slider partial clean preload-hidden">
        <div class="title">
            <h2>
                WETEN WAT NOG MEER invloed heeft
                <span>OP JE PENSIOEN? bekijk dan ook</span>
            </h2>
        </div>
        <div class="content">
            <div id="jx-slider-5"></div>
            <div id="jx-slider-6"></div>
        </div>
    </section>
    <div class="page-loading">&nbsp;</div>*@

Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@using System.Web.Optimization


@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <title>@CurrentPage.Name</title>
    <meta charset="utf-8">
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-scale=1.0,maximum-scale=1,minimum-scale=1,user-scalable=0" name="viewport">
    <meta content="yes" name="apple-mobile-web-app-capable">
    @*<link rel="stylesheet" href="css/app.css">*@
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script>
        var siteurl = '@Request.Url.GetLeftPart(UriPartial.Authority)';
    </script>


</head>
<body>
    <div>
        Main Menu
        @{Html.RenderPartial("NavMenu");}
    </div>

    @RenderBody()


    

@Styles.Render("~/bundles/css")
@Scripts.Render("~/bundles/scripts")


    <script data-main="@Request.Url.GetLeftPart(UriPartial.Authority)/src/js/app" src="~/vendor/requirejs/require.js"></script>
   
</body>
</html>

Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

Views/Partials/NavMenu.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the css class "current".
*@

@{ var selection = CurrentPage.Site().Children.Where("Visible"); }

<ul>
    @foreach (var item in selection)
    {
        <li class="@(item.IsAncestorOrSelf(CurrentPage) ? "current" : null)">
            <a href="@item.Url">@item.Name</a>
        </li>
    }
</ul>

Views/Partials/Poll.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

    @{
        var answers = Model.Content.Children.Where("Visible");

        if (answers != null)
        {

            using (Ajax.BeginForm("Submit", "Poll", new AjaxOptions
            {
                HttpMethod = "POST",
                UpdateTargetId = "target",
                InsertionMode = InsertionMode.Replace

            }, new { @class = "uk-form", @action = "/umbraco/Surface/Poll/Submit" }))
            {
                <h4>
                    @CurrentPage.question
                </h4>
                <p>Selecteer hieronder uw antwoord</p>

                @Html.Hidden((string)CurrentPage.Id.ToString())
                foreach (var item in answers)
                {
                    <div class="uk-form-row">
                        @Html.RadioButton("answerlist", item.Id, new { @id = item.Id })
                        @Html.Label((string)item.GetPropertyValue("possibleAnswer").ToString(), new { @for = item.Id })
                    </div>
                }
                <div class="uk-form-row">
                    <input type="submit" value="Stem" class="uk-button uk-button-primary uk-button-large">
                </div>
            }
        }
    }
<div id="target"> </div>

Views/Partials/Trend Counter.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


<section class="section text preload-hidden">
    <div class="content">
        <h2>
            EEN BAAN VOOR HET <span>LEVEN IS VERANDERD IN</span> Leven vol met banen
        </h2>
        <p>
            Een baan voor het leven is veranderd in een leven vol banen. We switchen makkelijk van baan, maar ook van sector. Soms zitten we zelfs even zonder werk en we beginnen steeds vaker als zelfstandige.
        </p>
    </div>
</section>
<section class="section text faded skew-inversed preload-hidden">
    <div class="content">

        @{ var selection = Model.Content.Children.Where("Visible");

         foreach (var item in selection)
         {

            <div class='uk-table @((bool)item.GetPropertyValue("leftRight") ? "uk-text-right" : "uk-text-left") '>
                <div>

                    @item.GetPropertyValue("text")

                </div>
                <div><img src="@Umbraco.Media(item.GetPropertyValue("image")).Url" alt="@item.Name" title="@item.Name"></div>
            </div>
         }
        }

    </div>
</section>

Views/Partials/Trend Image.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@*<div>
    <p>@CurrentPage.pageName</p>
    <div>
        @{
            if (CurrentPage.HasValue("image"))
            {
                var dynamicMediaPickerSingle = CurrentPage.image;
    <img src="@Umbraco.Media(Convert.ToInt32(dynamicMediaPickerSingle)).Url" style="width:200px;height:200px;" alt="" />
            }
        }
    </div>

</div>*@


<h1>
    Trend Image @CurrentPage.pageName
</h1>
<section class="section text preload-hidden">
    <div class="content">

        <h2>
            EEN BAAN VOOR HET <span>LEVEN IS VERANDERD IN</span> Leven vol met banen
        </h2>
        <p>
            Een baan voor het leven is veranderd in een leven vol banen. We switchen makkelijk van baan, maar ook van sector. Soms zitten we zelfs even zonder werk en we beginnen steeds vaker als zelfstandige.
        </p>
    </div>
</section>

Views/Partials/Trend Poll.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    var polls = Model.Content.Descendants("poll").Where("Visible").FirstOrDefault();
}


<section class="section slider compact preload-hidden">
    <div id="jx-slider-3"></div>
    <div class="widget">
        <div class="content">

            <p>
                Steeds meer mensen hebben steeds meer verschillende pensioenpotjes. De kans is ook groot dat je tussen die potjes ‘onderbrekingen’ hebt; periodes dat je geen pensioen hebt opgebouwd.
            </p>
            <div class="widget-intreaction">

                @{

                    if (polls != null)
                    {
                        if (HttpContext.Current.Request.Cookies["vote"] == null)
                        {
                            Html.RenderPartial("Poll", polls);
                        }
                        
                    }
                }


            </div>
        </div>
    </div>
</section>

Views/Partials/Trend Random Slider.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

<h1>Trend Random Slider</h1>




@*<div>

    @if (Model.Content.HasValue("imagePiker"))
    {
        var heroBannerList = Model.Content.GetPropertyValue<string>("imagePiker").Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
        var heroBannerCollection = Umbraco.TypedMedia(heroBannerList).Where(x => x != null);
        foreach (var heroBanner in heroBannerCollection)
        {
            <img src="@heroBanner.Url" style="width:200px;height:200px;" alt="@heroBanner.Name" />
        }
    }



</div>*@


<section class="section slider preload-hidden">
    <div class="uk-grid">
        <div class="uk-width-1-5">
            <div class="uk-table">
                <div class="uk-cell">
                    <div class="content">
                        <h2>
                            GOED OM
                            <span>TE WETEN</span>
                        </h2>
                        <p>Je werkt 1 dag voor je pensioen</p>
                    </div>
                </div>
            </div>

        </div>
        <div class="uk-width-3-5">
            <div id="jx-slider-4"></div>
        </div>
        <div class="uk-width-1-5">
            <div class="uk-table">
                <div class="uk-cell">
                    <div class="content">
                        <h2>
                            GOED OM
                            <span>TE DOEN</span>
                        </h2>
                        <p>
                            Check jouw verschillende pensioenpotjes op
                            <a href="http://mijnpensioenoverzicht.nl">mijnpensioenoverzicht.nl</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Partials/Trend Simple Slider.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

<h1>Trend Simple Slider partiak view</h1>
	
<section class="section slider preload-hidden">
    <div id="jx-slider-2"></div>
</section>


@*<div>

    @if (Model.Content.HasValue("imagePiker"))
    {
        var heroBannerList = Model.Content.GetPropertyValue<string>("imagePiker").Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
        var heroBannerCollection = Umbraco.TypedMedia(heroBannerList).Where(x => x != null);
        foreach (var heroBanner in heroBannerCollection)
        {
            <img src="@heroBanner.Url" style="width:200px;height:200px;" alt="@heroBanner.Name" />
        }
    }


</div>*@

Views/Partials/Trend Subscription.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


<section class="section clean partial widgets preload-hidden">
    <div class="title">
        <h2>
            Leef je van dag tot dag
            <span>Of kijk je verder vooruit?</span>
        </h2>
    </div>
    <div class="uk-grid">
        <div class="uk-width-1-3 skew fb">
            <div class="content">
                <p>
                    Blijf op de hoogte <br>via Facebook.
                </p>

                <div class="uk-text-center">
                    <img src="@Umbraco.Media(1133).Url" alt="Facebook" title="Facebook">
                    <br>
                    <a href="#" class="uk-button uk-button-primary uk-button-large">Naar facebookpagina</a>
                </div>

            </div>
        </div>
        <div class="uk-width-1-3 skew subscribe">
            <div class="content">
                <p>
                    Op mijnpensioenoverzicht.nl kun je snel <br>en simpel checken hoe jij ervoor staat.
                </p>
                <div class="uk-text-center">
                    <img src="@Umbraco.Media(1137).Url" alt="mijnpensioenoverzicht.nl" title="mijnpensioenoverzicht.nl">
                    <br>
                    <a href="http://mijnpensioenoverzicht.nl" class="uk-button uk-button-default uk-button-large">
                        <span>mijn</span>pensioenoverzicht.nl
                    </a>
                </div>
            </div>
        </div>
        <div class="uk-width-1-3 skew contact">
            <div class="content">
                <form class="uk-form">
                    <p>
                        Schrijf je in voor <br>
                        De Tijd van Je Leven nieuwsbrief.
                    </p>
                    <div class="uk-form-row">
                        <input type="text" name="email" placeholder="Uw voor en achternaam">
                    </div>
                    <div class="uk-form-row">
                        <input type="password" name="email" placeholder="Uw emailadres@voorbeeld.iets">
                    </div>
                    <div class="uk-form-row">
                        <input type="submit" class="uk-button uk-button-primary uk-button-large" value="aanmelden">
                    </div>
                </form>
                <img src="@Umbraco.Media(1138).Url" class="hover-view">
            </div>
        </div>
    </div>
</section>

<section class="section slider partial clean preload-hidden">
    <div class="title">
        <h2>
            WETEN WAT NOG MEER invloed heeft
            <span>OP JE PENSIOEN? bekijk dan ook</span>
        </h2>
    </div>
    <div class="content">
        <div id="jx-slider-5"></div>
        <div id="jx-slider-6"></div>
    </div>
</section>

Views/Partials/Trend Text.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


<h1>
    Trend Text @CurrentPage.pageName
 </h1>
<section class="section text preload-hidden">
    <div class="content">
        <h2>
            EEN BAAN VOOR HET <span>LEVEN IS VERANDERD IN</span> Leven vol met banen
        </h2>
        <p>
            Een baan voor het leven is veranderd in een leven vol banen. We switchen makkelijk van baan, maar ook van sector. Soms zitten we zelfs even zonder werk en we beginnen steeds vaker als zelfstandige.
        </p>
    </div>
</section>

Views/SimplePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

<div>
    @{
        if (CurrentPage.HasValue("image"))
        {
            var dynamicMediaPickerSingle = CurrentPage.image;
      
            <img src="@Umbraco.Media(Convert.ToInt32(dynamicMediaPickerSingle)).Url" style="width:200px;height:200px;" alt="" />
        }
    }

</div>

<div>
    @CurrentPage.text
</div>

Views/Trend.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@{ var selection = Model.Content.Children.Where("Visible"); }

<h1>@CurrentPage.colorSpectrum</h1>
<section class="section slider preload-hidden">
    <div id="jx-slider-1"></div>
</section>

@foreach (var item in selection)
{
    switch (item.DocumentTypeAlias)
    {
        case "pollPage":
            Html.RenderPartial("Trend Poll", item);
            break;
        case "counterAndText":
            Html.RenderPartial("Trend Counter", item);
            break;
        case "randomSlider":
            Html.RenderPartial("Trend Random Slider", item);
            break;
        case "simpleSlider":
            Html.RenderPartial("Trend Simple Slider", item);
            break;
        case "subscriptionPage":
            Html.RenderPartial("Trend Subscription", item);
            break;
        default:

            break;
    }
}
<div class="page-loading">&nbsp;</div>